name: GoLang Test
on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [KF9, KF10]
        go-version: [ '1.18', '1.19']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: go build -v ./...

      - name: Test
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          envfile: ${{ secrets.ENV_FILE }}
        run: echo $envfile | base64 --decode > .env && cat .env && go test -v ./...



